name = "AccountableEntities"
version = "0.1.0"
defaultTargets = ["StructuralExplainability"]
keywords = [
"formal-ontology",
"identity-regimes",
"structural-explainability",
"accountability",
"semantic-interoperability",
"formal-verification",
"theorem-proving",
"lean4",
"necessity-and-sufficiency",
"structural-constraints"
]

license = "MIT"

[[lean_lib]]
name = "StructuralExplainability"

[[lean_exe]]
name = "ae"
root = "Main"
